theme: minima
title: "Murilo Costa - DevOps Journey"
description: "Documentando minha jornada de estudante a DevOps Engineer"
exclude: ["README.md"]

github_username: MuriloCosta29
linkedin_username: carlosmuriloocf
